import { Poppins } from '@/shared/lib/styles/fonts';
import '@/shared/lib/styles/global.css';
import { Header } from '@/widgets/header/Header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={Poppins.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
